### ISSUE TITLE
custom storage log location

### ISSUE THREAD

**Issue by nassajis** [ARCANEDEV/LogViewer#23]
add custom storage log location
or 
read all file and folder log file
![11](https://cloud.githubusercontent.com/assets/10128882/10930793/e70dccd0-82d6-11e5-8559-55b14fd87957.png)

tnx :+1:

**Comment by arcanedev-maroc** [comment]
Hi @nassajis, thanks for your suggestion.

Note that **all log files is managed by laravel** and **its use only a single folder**.

So, i don't see what you want to do and i'm not sure if your folder `2` is created manually or inside your laravel application because is not the case for everyone.

The only thing that i can do is to add a new method like `LogViewer::setPath()` or something to set a custom location dynamically but it's not going to load both of them (without default localtion).

Or/And adding the `path` value in the config file to be more flexible.

Of course i'm open for any other suggestion/PR. :+1:

**Comment by arcanedev-maroc** [comment]
I've added a new method `LogViewer::setPath('custom-path')` to load a custom log folder.

You can also edit the logs path from the config file.

This will be released for LogViewer `>= 3.6.0`. You can also the `dev-master` version.

Close : #25
