### ISSUE TITLE
0 Logs

### ISSUE THREAD

**Issue by EskindirA** [ARCANEDEV/LogViewer#233]
- LogViewer Version: 4.6
- Laravel Version: 5.7.1
- PHP Version: 7.2.0

### Description:
upgraded my 5.4 application to 5.7 and installed log-viewer, 
changed to     'log' => env('LOG_CHANNEL', 'daily'), in config/app
and now there are 0 daily logs.

run config:cache
and composer dump-autoload
still nothing.
### Steps To Reproduce:

found the below message inside the log

Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined.

**Comment by arcanedev-maroc** [comment]
The log system has been changed since laravel `5.6`.

You have a new config file for **logging**: https://github.com/laravel/laravel/blob/master/config/logging.php

Please follow the official documentation to upgrade your application.

Plus: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#application-requirements

**Comment by EskindirA** [comment]
yes, the logging.php config file was missing. It works now. Thanks.
