### ISSUE TITLE
LogViewer works with the 'stack' driver as long as you have 'daily' set in your channels

### ISSUE THREAD

**Issue by hotsaucejake** [ARCANEDEV/LogViewer#252]
```
'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['daily', 'slack'],
        ],
```

I can access the log-viewer route fine and it displays all of the daily log entries.  HOWEVER, `php artisan log-viewer:check ` understandably fails.  Not a major issue because it works otherwise.  

But using the 'stack' driver DOES work.

**Comment by arcanedev-maroc** [comment]
This package only supports the `daily` channel. 

That's why i recommend to use `daily` if you want to use all the LogViewer features.

Thanks for the feedback BTW :+1:

**Comment by viraljetani** [comment]
Is there any upgrade planned to implement multiple stack channels? To be using it on large scale projects it will usually need to track multiple stack channels.. 

Would be a great Feature addition to this wonderful piece of work..!!

**Comment by arcanedev-maroc** [comment]
Feel free to make a PR for this feature :+1:

**Comment by picbenoit** [comment]
Hi @arcanedev-maroc 

As other people here, I need more than just daily channel for my log. I'm using Slack channel to log my errors to have more visibility and responsiveness.

`            'channels' => ['daily', 'slack'],
`

When you said : "That's why i recommend to use daily if you want to use all the LogViewer features.", which features will not be available with my configuration if daily channel is included in stack driver ?

Ben
