### ISSUE TITLE
Please add "Usage" section of documentation

### ISSUE THREAD

**Issue by zingfrid** [ARCANEDEV/LogViewer#265]
I'm new to Laravel/PHP and already spend 2 weeks to get this embedded to my side, but no success. Can you please, add "Usage" section of documentation with an explanation of how to use LogViewer in the HomeController of default Laravel installation.

**Comment by arcanedev-maroc** [comment]
Hi @zingfrid,

Instead of waiting the complete release of the documentation, you can start by using the `log_viewer()` helper (easy way).

The available methods of the `log_viewer()` helper is listed on: https://github.com/ARCANEDEV/LogViewer/blob/master/src/Contracts/LogViewer.php

You can check the existing Routes/Controller/Views to start quickly.

Of course you can also submit a PR to complete the documentation.

Related: #227
