### ISSUE TITLE
Fixing the Route for Error Page (403)

### ISSUE THREAD

**Issue by mavinothkumar** [ARCANEDEV/LogViewer#290]
- LogViewer Version: 4.5
- Laravel Version: 5.6
- PHP Version:7.2

### Description:
I have set the middleware for logviewer.  So if the unauthorised user tried to enter the url its redirecting to /error/403 . But I dont have route or url for this by default. I can add this in my route file. Is there any way to override the error route or url?

**Comment by arcanedev-maroc** [comment]
Why are you redirecting to an error page? Try to use `abort(403)` and {Exception Handler](https://laravel.com/docs/5.6/errors#the-exception-handler)

And your question/issue is not related to the package

**Comment by mavinothkumar** [comment]
No Am not redirecting it to /error/403.

Ok. Let me ask you a simple question, You have declared a ARCANEDEV_LOGVIEWER_MIDDLEWARE=web,auth in .env and a user one who doesn't logged in trying to access the URL. What would happen?

Hope right now its redirecting to error/403 is there an way to change this URL for custom route or url ?

**Comment by arcanedev-maroc** [comment]
The `web` middleware is for basic web requests (csrf token, session, ...)
The `auth` middleware is to check if the user is connected, otherwise, redirect to login page

Check the official laravel documentation for more details about the middleware

If you want to throw 403 error for unauthorized users, you need to create a custom middleware for that.

Before, you ask another question, do your research in forums because this is unrelated to this package

Example:

 * https://laravel.com/docs/5.6/authentication#protecting-routes
 * https://laravel.com/docs/5.6/middleware
 * https://github.com/ARCANEDEV/LogViewer/issues?utf8=✓&q=is%3Aissue+middleware

Thanks

**Comment by mavinothkumar** [comment]
Thanks for your polite response.
