### ISSUE TITLE
Target [Arcanedev\LogViewer\Contracts\LogViewer] is not instantiable while building [Arcanedev\LogViewer\Http\Controllers\LogViewerController].

### ISSUE THREAD

**Issue by JunaidKhan046** [ARCANEDEV/LogViewer#323]
- LogViewer Version: #.#.# 5.2
- Laravel Version: #.#.# 6.0
- PHP Version: #.#.# 7.2.0

### Description:
this log viewer is working perfectly on local-host server then i deployed the shared linux hosting the code shown this error  "Target [Arcanedev\LogViewer\Contracts\LogViewer] is not instantiable while building [Arcanedev\LogViewer\Http\Controllers\LogViewerController]. "

i can't understand this error why produce on my live server.

Kindly help me Thanks.

**Comment by arcanedev-maroc** [comment]
Try to remove the cached files in the `bootstrap/cache`

**Comment by JunaidKhan046** [comment]
I am update my bootstrap cache file manually  to local server to live file then update code.
My code is working fine
Thanks for guide me

**Comment by abdosaeedelhassan** [comment]
@arcanedev-maroc thank you for you package
i have the same problem
Target [Arcanedev\LogViewer\Contracts\LogViewer] is not instantiable while building [Arcanedev\LogViewer\Commands\PublishCommand].
`
that shown in terminal only when install this package as a submodule inside project, but when i installed as default it work fine,
i want to implemented as submodule because i want make some contribution.
Thank you
`
