### ISSUE TITLE
Adding the ability to exclude logs containing a phrase

### ISSUE THREAD

**Issue by janzankowski** [ARCANEDEV/LogViewer#348]
- LogViewer Version: v7.0.0
- Laravel Version: 7.x
- PHP Version: 7.2.31

### Description:

When searching through logs, it would be very helpful to be able to filter out entries containing a given phrase. Often, logs are full of intermittent problems that we know are of low priority, and which can swamp out real issues. Also, often we don't know what to search for (new exceptions are usually a surprise) but we know what NOT to search for (these intermittent network issues, etc).

I suggest the usual search query syntax with leading minus sign.

Finally, this is extra and material for another issue, but the above would go hand in hand with some mechanism for phrases, for a complete solution allowing for a query string like this:
`-"Connection timed out" -"Invalid authorization token" -"User input validation failure"`

Thank you for considering this (& a great package!)

**Comment by arcanedev-maroc** [comment]
Hi @janzankowski,

Have you tried to extend the package in your project? It's hard to cover all the use cases for everyone (+ the maintenance cost)

But this package is open for modification & customization. Check #83 for more details

**IMPORTANT:** Use this package as an API instead of a predefined UI package
