### ISSUE TITLE
Support of channels

### ISSUE THREAD

**Issue by bernhardh** [ARCANEDEV/LogViewer#368]
Is it possible to use different log channels at the same time?

Currently, you can configure the file prefix with the config `log-viewer.pattern.prefix`, but this is an application wide settings.

In the newer versions of laravel (I think `>=5.6`) you can define different logging channels like this:

```php
return [
    'channels' => [
        'daily' => [
            'driver' => 'daily',
            'path' => storage_path('logs/laravel.log'),
            'level' => 'debug',
            'days' => 14,
        ],

        'custom1' => [
            'driver' => 'daily',
            'path' => storage_path('logs/custom1.log'),
            'level' => 'debug',
            'days' => 14,
        ],
    ],
];
```

where logging will create files like `logs/laravel-2020-10-13.log` for the `daily` channel or `logs/custom1-2020-10-13.log` for the `custom1` channel.

With the current implementation of this package, I can't view both channels, since I would have to decide in the config, if a wanna use files with the prefix `laravel-` or `custom1-`.

Other packages (like https://github.com/rap2hpoutre/laravel-log-viewer) are able to show these logs:

![image](https://user-images.githubusercontent.com/642292/95850303-e70f0c80-0d50-11eb-85af-406cfb32282d.png)

**Comment by arcanedev-maroc** [comment]
I can't fully understand why you're using the same `daily` driver for both of them ? This is just duplication!

But is you insist to have this feature, this package is **open for extension**

All you need to do is: 

 * Disable the default routes and copy them in your app: [LogViewerRoute](https://github.com/ARCANEDEV/LogViewer/blob/master/src/Http/Routes/LogViewerRoute.php)
 * Add a prefix to the log-viewer routes. Instead of `log-viewer/logs/{date}` (for example), you can use something like `log-viewer/{log-channel}/logs/{date}` which `log-channel` is your driver's key, in your case is `daily` and `custom1` then you add a route binding for `log-channel` wildcard to switch the log-viewer's glob pattern.
 * Then you need to change the views (they are publishable): Adding a select input to switch between the channels and links/forms (now the `route()` helper requires a `log-channel` parameter and you can grab it from the `request()` helper)
* Create a new `LogViewerController ` (you can extend from the default) and change anything that requires `log-channel` (like redirection for example)

And i think that's all you need to do!

For any question related to customization, check this [label](https://github.com/ARCANEDEV/LogViewer/issues?q=is%3Aissue+is%3Aclosed+label%3Acustomization)

**Comment by bernhardh** [comment]
Thanks for feedback. I was just wondering, if it would be possible / build in and I don't see it.

> I can't fully understand why you're using the same daily driver for both of them ? This is just duplication!

To separete different logs. For example, I have a regular application log (for the frontend for regular users), a log for the backend and a log for cronjob / scheduled tasks. So if a cronjob which runs every minute fails, it would fill up the log in hours and it would be very hard to see the logs of the other sections, because of these "spam" entries. This is especially anoying, since this cronjob task can fail often, since it depends on third party resources which aren't available all the time.

**Comment by arcanedev-maroc** [comment]
I don't want to implement this "feature" because i prefer it "minimal but extendable" and not everybody use multiple `daily` driver.

About the `frontend` & `backend` logs, don't forget to use a [specific channel](https://laravel.com/docs/8.x/logging#writing-to-specific-channels) instead of the default stack. Otherwise, you will end up with duplicated entries
