### ISSUE TITLE
I want to customize the names of the levels

### ISSUE THREAD

**Issue by DanielKimmich** [ARCANEDEV/LogViewer#438]
- LogViewer Version:  8.3.0
- Laravel Version: 8.83.27
- PHP Version:  7.4.33

### Description:
I want to customize the names of the levels and it is not taking said names,

### Steps To Reproduce:
the translation was published
php artisan log-viewer:publish --tag=translations

The file was modified for Spanish in lang/vendor/log-viewer

{
    "Date": "Fecha",
    "The list of logs is empty!": "La lista del log está vacía!",
    "All": "Todos",
    "Emergency": "Auditoria",
    "Alert": "Alerta",
    "Critical": "Criticos",
    "Error": "Errores",
    "Warning": "Advertencia",
    "Notice": "**LOGIN**",
    "Info": "Info",
    "Debug": "Debug"
}

on the web it keeps showing as "**Aviso**"

**Comment by DanielKimmich** [comment]
doing a couple of tests I could see that the file "es.json" is looking for it from the folder "lang"

and the publication is made in the folder "lang/vendor/log-viewer"

**Comment by bluedasher13** [comment]
I found that the **[loadTranslations()](https://github.com/ARCANEDEV/Support/blob/7abc5802512329fd3dccbb467ad8e8e77e768f5c/src/Providers/Concerns/HasTranslations.php#L58)** method will always only read files in `{base_path}/vendor/arcanedev/log-viewer/translations`, instead of reading the files in `{base_path}/resources/lang/vendor/log-viewer` pointed to by the **[getTranslationsDestinationPath()](https://github.com/ARCANEDEV/Support/blob/7abc5802512329fd3dccbb467ad8e8e77e768f5c/src/Providers/Concerns/HasTranslations.php#LL38C1-L38C1)** method.

**ARCANEDEV/Support/blob/master/src/Providers/Concerns/HasTranslations.php**:
https://github.com/ARCANEDEV/Support/blob/master/src/Providers/Concerns/HasTranslations.php#LL38C1-L64C1

**Comment by arcanedev-maroc** [comment]
I've released a new fix, try to update your dependencies and see if it's solves your issue
Fix: https://github.com/ARCANEDEV/Support/commit/f401e1a859fe4e84331986d18ee0313e37e89810
