### ISSUE TITLE
Group by exception type

### ISSUE THREAD

**Issue by garygreen** [ARCANEDEV/LogViewer#56]
It would be cool if you could group by exception types, similar to Bugsnag. I find that to be more useful than grouping by emergency level. That way you can also gauge how many exceptions of a certain type there are.

**Comment by arcanedev-maroc** [comment]
Hi @garygreen, thanks for using the log viewer package.

I think it's complicated to implement this feature because the package read only the logs and display the content.

And it's completely different from the Bugsnag (editing the Laravel error handler to send the exceptions to the Bugsnag's server).

So the question is: how to extract the exception types from the log files ?
