### ISSUE TITLE
How to use authentication middleware with this plugin?

### ISSUE THREAD

**Issue by Lucassith** [ARCANEDEV/LogViewer#69]
Hi.

I am looking for the solution on how to authenticate user by adding middleware to the config file. I have probably the same problem as #63 has. According to the laravel docs 

```php
if(Auth::check()){
            
}
```
should be true if the user is logged in. This is working for each route in my routes.php but not if I use it with the log-viewer config.

**Comment by arcanedev-maroc** [comment]
Hi @Lucassith,

You don't need to repeat yourself by adding the `Auth::check()` for each route in your `routes.php`.

Try middleware instead, check the [documentation for more details](https://laravel.com/docs/5.2/middleware#registering-middleware).

So you can apply the [auth](https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L47) middleware to the log-viewer routes with the config file like this:

```php
    'route'         => [
        'enabled'    => true,
        'attributes' => [
            'prefix'     => 'log-viewer',
            'middleware' => ['auth'],
        ],
    ],
```

**Comment by Lucassith** [comment]
@arcanedev-maroc thanks for your response. However it does not resolve my problem.

log-viewer.php

```php
'route' => [
        'enabled' => env('APP_DEBUG', false),

        'attributes' => [
            'prefix' => 'admin/log-viewer',

            'middleware' => ['globaladmin'],
        ],
    ],
```

globaladmin middleware:

```php
use Illuminate\Contracts\Auth\Guard;
use Auth;

class GlobalAdminMiddleware
{

protected $auth;

public function __construct(Guard $auth)
    {
        $this->auth = $auth;
    }

public function handle($request, Closure $next)
    {
        if ($this->auth->guest() || !Auth::user()->is_admin) {
            if ($request->ajax()) {
                return response('Unauthorized.', 401);
            } else {
                return redirect()->route('login');
            }
        }
        if (Auth::getUser()->is_suspended') {
            Auth::logout();

            return redirect('/suspended');
        }

        return $next($request);
    }
}
```

Every time I go to the http://my.app/admin/log-viewer I am being redirected to the login and then to the main page because I am already logged in. I am global admin.

Even if I use the default auth middleware I am being redirected to the login -> main page.

And as I said, if I use this middleware inside my own routes it is working well.

**Comment by arcanedev-maroc** [comment]
So, if you go to http://my.app/admin/log-viewer and you've been redirected to the login page, that means the middleware is working for the log-viewer routes.

You need to check your routes and your middleware(s) because i don't have this issue with any of my projects (LogViewer in backend side => Administration with auth middleware(s) ).

**Comment by Lucassith** [comment]
I was able to make it work.

In L5.2 middleware groups were introduced. In order to make Auth work you need to use "web" group which contains session and csrf middlewares.

Thank you @arcanedev-maroc for help and this great plugin.

**Comment by arcanedev-maroc** [comment]
You're welcome :+1:

**Comment by angoz** [comment]
@Lucassith I have the same problem as you in L5.2. How did you fix it? Thank you.

**Comment by amitgds** [comment]
Hi arcanedev-maroc,

I have used this log viewer module in my application but unable to apply authentications on it. I have tried the suggested way you have mentioned above but it is not working for me. Can you please let me know what else I have to do so that only authenticated users can access it.  

Here is the code which I have used in my config/log-viewer.php 

    'route'         => [
        'enabled' => true,
        'attributes' => [
            'prefix'     => 'log-viewer',
                'middleware' => ['web','auth'],
        ],
    ],

When I have added these middle-ware  ideally user should be redirected to login page if they are not logged in but nothing happen. any body can access it.  


Kind Regards

**Comment by cwilby** [comment]
Fun fact for anybody reading this in the future - you can re-use the gate in Laravel Nova for convenience.

```php
...
'middleware' => ['nova']
...
```

**Comment by patelmm** [comment]
not working, any one have solution ?
