### ISSUE TITLE
Do not use aliases in the package

### ISSUE THREAD

**Issue by atehnix** [ARCANEDEV/LogViewer#81]
Do not use aliases in the package.
This forces the user to include aliases in the app configuration, even if he does not use them in own application.

Moreover, you can get unpredictable behavior if the alias will refer to the other facade (not the default).

See: [navigation.blade.php](https://github.com/ARCANEDEV/LogViewer/blob/master/resources/views/_template/navigation.blade.php#L15)  and also check other files, just in case.

**Comment by arcanedev-maroc** [comment]
What do you mean by aliases ??

Are you talking about `Route::is()` method or the route name `'log-viewer::dashboard'` ?

**Comment by arcanedev-maroc** [comment]
Laravel includes `Route` facade [out of the box](https://github.com/laravel/laravel/blob/master/config/app.php#L220), so i don't see the issue here. [Another example](https://github.com/laravel/laravel/blob/master/routes/web.php#L14-L16).

**Comment by atehnix** [comment]
OK. If my arguments are not convincing for you, then at least you can believe the official documentation.
https://laravel.com/docs/master/packages#a-note-on-facades

:)

**Comment by arcanedev-maroc** [comment]
This is another solution, you can publish the `LogViewer` views (including the `navigation.blade.php`) and change it as you want.

**Comment by atehnix** [comment]
I already did. I just wanted to help other users of your package and at the same time help you to understand why such a solution is more correct. I believe that in the future you will write many good packages.

Thank you. I will not disturb you about this, sorry. )

**Comment by arcanedev-maroc** [comment]
Yes, i understand what you want to achieve. But for the time being, all users has no issue with this solution.

And of course, *nothing is perfect*. This is not a wrong way because the facade is only used in views and customizatable by anyone.

If you change the default laravel installation like **removing all facades**, this package will works if you made the same change by **removing the facades from LogViewer views** and it's done.

Feel free to make any suggestion to improve the package.

Thanks for making this issue and using the package.
