### ISSUE TITLE
Route not found with Laravel 5.3

### ISSUE THREAD

**Issue by ilvalerione** [ARCANEDEV/LogViewer#82]
I used this great package in all my software.

Now i'm getting started with Laravel 5.3 so i installed a package with 

`composer require arcanedev/log-viewer`

and composer give me a 3.10 version (not 4).

later I registered a service provider and published configuration.

I also executed `check` command, and all things seems Ok.

When i go in `http://localhost/[my-folder]/public/log-viewer` I'm getting a not found laravel exception:

![immagine](https://cloud.githubusercontent.com/assets/13559278/18583591/c9a0b7d2-7c0b-11e6-8e69-8c2c14d01601.png)

Have you some help?

**Comment by arcanedev-maroc** [comment]
This is 404 error you've got.

I've just test the package with Laravel `v5.3` and it works with no problem. 

The latest version of `arcanedev/log-viewer` is `3.10` (v4 will be released this weekend).

Can you check your routes by running the `route:list` command ?

You need to avoid routes like `Route::get('/{wildcard}')` because it'll consider '/log-viewer' as a wildcard.

Check also `http://localhost/[my-folder]/public/log-viewer/logs`.

**Comment by cjmaxik** [comment]
Issue is for me too.
I have 3 simple routes, list has all of LogViewer routes.

**Comment by arcanedev-maroc** [comment]
@ilvalerione & @cjmaxik: Can you give me the routes list you've got (with middleware and stuff) ?

**Comment by ilvalerione** [comment]
The url in the browser is case sensitive!

**Comment by arcanedev-maroc** [comment]
@ilvalerione: so there is no issue ?

**Comment by ilvalerione** [comment]
For me was the url written without respect case densitive. The package was ok for me.

**Comment by dionejpmc** [comment]
http://localhost/[my-folder]/public/log-viewer/logs workerd for me
